import './globals.css'
import 'bulma/css/bulma.min.css';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// I am using Inter font from Google Fonts
// https://fonts.google.com/specimen/Inter
// You can use any font you like
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
